apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: microservices-demo
description: main application pipeline
serialPipeline:
 stages:
 - targetId: dev
   profiles: []
 - targetId: prod
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev
description: development cluster
gke:
 cluster: projects/gke-demo-347012/locations/australia-southeast1/clusters/dev-cluster

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod
description: production cluster
requireApproval: true
gke:
 cluster: projects/gke-demo-347012/locations/australia-southeast1/clusters/prod-cluster
 
 